export const environment = {
  production: true,
  API_KEY: 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNDQ3MzI5OTJkNGFkYjc0ODI3MDhlMDhhZGE0NmZjMyIsIm5iZiI6MTcyODI3MjMxMi42NzM0ODEsInN1YiI6IjY2ZmVkMTgyOWViZWExOTAwNmY3ZTNjMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.PLD6maLUzC-xzOy-KrW8ae-jSz6CLF5gRi4ailjDAQA',
};
